apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080

