name: Go Web App CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: public.ecr.aws/o9g6t1r4
  ECR_REPOSITORY: go-web-app

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go build
        working-directory: static
        run: go build -v ./...

      - name: Go test
        working-directory: static
        run: go test ./...

      - name: Login to Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push Docker image
        working-directory: static
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

